import { ApolloProviders } from './providers';
import React from "react";
import { Outfit, Saira } from 'next/font/google';
import '@mantine/core/styles.css';
import '@mantine/code-highlight/styles.css';

import { ColorSchemeScript, MantineProvider, mantineHtmlProps } from '@mantine/core';
import { theme } from '@/theme/theme';
// import next from 'next';


// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

const saira = Saira({ 
  subsets: ['latin'],
  display: 'swap', 
});

const outfit = Outfit({ 
  subsets: ['latin'],
  display: 'swap', 
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" {...mantineHtmlProps}>
      <head>
        <ColorSchemeScript />
      </head>
      <body>
        <ApolloProviders>
          <MantineProvider theme={theme} defaultColorScheme="auto">
            {children}
          </MantineProvider>
        </ApolloProviders>
      </body>
    </html>
  );
}
